// Docs consistency guard: the judge-facing prose must not contradict itself or the codebase.
//
// This exists because a single stale number ("177 tests" while the suite is 205, "13 gates" while
// there are 15) is a disproportionate trust leak — a judge who spots one inconsistency starts
// doubting every other figure. So we scan EVERY human-authored doc (not just the top two) and fail
// on: a missing required file, a test/gate count that disagrees with the canonical value, or an
// un-negated overclaim ("guaranteed alpha", "risk-free", …).
//
// Generated artifacts (FINAL_VERIFICATION.md, FINAL_UAT_MATRIX.md, evidence/**) are excluded — they
// are regenerated by their own tooling and should not be hand-edited.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// Canonical values the prose must track. Bump these when the suite/gate set genuinely changes — the
// guard then forces every doc to follow, which is the whole point.
const CANONICAL_TESTS = 215;
const CANONICAL_GATES = 15;

// Must exist (a judge links straight to these).
const required = [
  "README.md",
  "SUBMISSION.md",
  "PROJECT.md",
  "docs/BITGET_NATIVE_PROOF.md",
  "docs/PNL_CLAIM_STANDARD.md",
  "docs/CLAIM_LEDGER.md",
  "docs/SECURITY_BOUNDARIES.md",
  "EVALUATION_STANDARD.md",
];

// Every human-authored doc that gets scanned for staleness/overclaims.
const scanned = [
  "README.md",
  "SUBMISSION.md",
  "PROJECT.md",
  "EVALUATION_STANDARD.md",
  "AGENT_INTENT_SPEC.md",
  "TOKEN_SAFETY_STANDARD.md",
  "verification-log.md",
  "docs/BITGET_NATIVE_PROOF.md",
  "docs/BITGET_AGENT_HUB_COMPAT.md",
  "docs/CLAIM_LEDGER.md",
  "docs/EXECUTION_INTEGRITY.md",
  "docs/PNL_CLAIM_STANDARD.md",
  "docs/SECURITY_BOUNDARIES.md",
  "docs/SUBMISSION_RUNBOOK.md",
  "docs/FRONTEND_UX_SPEC.md",
  "docs/JUDGE_QUICKLOOK.md",
  "sdk/README.md",
  "playbook/btc-convergence/README.md",
  "playbook/raapl-convergence/README.md",
];

// Overclaim phrases are only stale when ASSERTED. The honesty docs legitimately say "we do NOT claim
// guaranteed alpha" / "not risk-free" — those must pass. We look back a short window for a negation.
const NEGATION = /\b(no|not|never|without|isn'?t|aren'?t|don'?t|does\s?n'?t|do\s+not|does\s+not|should\s+not|cannot|can'?t|avoid|reject|rejects|disallow|disallowed|refuse|refuses|no\s+real)\b[^.]{0,40}$/i;
const OVERCLAIMS = [
  { re: /\bguaranteed\s+(?:alpha|profit|returns?)\b/gi, reason: "guaranteed-return overclaim" },
  { re: /\brisk[-\s]?free\b/gi, reason: "risk-free overclaim" },
  { re: /\balways\s+profitable\b/gi, reason: "always-profitable overclaim" },
  { re: /\bcan'?t\s+lose\b/gi, reason: "can't-lose overclaim" },
  { re: /\b100%\s+win(?:\s+rate)?\b/gi, reason: "100%-win overclaim" },
  { re: /\blive\s+trade\s+executed\b/gi, reason: "live-execution overclaim" },
];

interface Stale { file: string; reason: string; match: string }

function scanText(file: string, text: string, stale: Stale[]): void {
  // Test count: every "<N> tests" must equal the canonical count.
  for (const m of text.matchAll(/\b(\d{2,4})\s+(?:unit\s+|property\s+)?tests?\b/gi)) {
    if (Number(m[1]) !== CANONICAL_TESTS) stale.push({ file, reason: `stale test count (canonical ${CANONICAL_TESTS})`, match: m[0] });
  }
  // Hard-gate count: every "<N> hard [risk] gates" must equal the canonical count.
  for (const m of text.matchAll(/\b(\d{1,3})\s+hard\s+(?:risk\s+)?gates?\b/gi)) {
    if (Number(m[1]) !== CANONICAL_GATES) stale.push({ file, reason: `stale gate count (canonical ${CANONICAL_GATES})`, match: m[0] });
  }
  // Overclaims, only when not negated by the preceding clause.
  for (const oc of OVERCLAIMS) {
    for (const m of text.matchAll(oc.re)) {
      const before = text.slice(Math.max(0, (m.index ?? 0) - 48), m.index ?? 0);
      if (!NEGATION.test(before)) stale.push({ file, reason: oc.reason, match: m[0] });
    }
  }
}

export function runDocsCheck(): boolean {
  const rows = required.map((file) => ({ file, exists: existsSync(join(process.cwd(), file)) }));
  const stale: Stale[] = [];
  for (const file of scanned) {
    const full = join(process.cwd(), file);
    if (!existsSync(full)) continue;
    scanText(file, readFileSync(full, "utf8"), stale);
  }
  const ok = rows.every((r) => r.exists) && stale.length === 0;
  writeFileSync(
    join(process.cwd(), "evidence", "docs-check.json"),
    JSON.stringify({ generatedAt: new Date().toISOString(), ok, canonical: { tests: CANONICAL_TESTS, gates: CANONICAL_GATES }, rows, stale }, null, 2) + "\n",
  );
  console.log(`NIGHTDESK DOCS CHECK ${ok ? "PASS" : "FAIL"}`);
  for (const r of rows) if (!r.exists) console.log(`✗ missing required doc: ${r.file}`);
  for (const s of stale) console.log(`✗ ${s.file}: ${s.reason} ("${s.match}")`);
  if (!ok) process.exitCode = 1;
  return ok;
}

if (process.argv[1]?.endsWith("docs-check.ts")) runDocsCheck();
