// AUTO-GENERATED by `npm run firewall:export` — do not edit by hand.
export const snapshotAt = "2026-06-18T16:21:46.851Z";
export const universe = [
  {
    "ticker": "AAPL",
    "cert": {
      "ticker": "AAPL",
      "trueGapPct": 0.0050446451092119775,
      "perpGapPct": -0.08232388568740596,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 82,
      "policy": "NORMAL",
      "evidence": [
        "true gap 0.01% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "TSLA",
    "cert": {
      "ticker": "TSLA",
      "trueGapPct": 0.02673864880695159,
      "perpGapPct": -0.0025457924415399256,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 67,
      "policy": "NORMAL",
      "evidence": [
        "true gap 0.03% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "NVDA",
    "cert": {
      "ticker": "NVDA",
      "trueGapPct": 0.007154099298905318,
      "perpGapPct": -0.11908447852906853,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 82,
      "policy": "NORMAL",
      "evidence": [
        "true gap 0.01% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "MSFT",
    "cert": {
      "ticker": "MSFT",
      "trueGapPct": 0.0013229963220690213,
      "perpGapPct": -0.23362018900796974,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 82,
      "policy": "NORMAL",
      "evidence": [
        "true gap 0.00% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "GOOGL",
    "cert": {
      "ticker": "GOOGL",
      "trueGapPct": -0.0013659149581489928,
      "perpGapPct": -0.10642942910163826,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 67,
      "policy": "NORMAL",
      "evidence": [
        "true gap -0.00% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "AMZN",
    "cert": {
      "ticker": "AMZN",
      "trueGapPct": 0.01645278051990459,
      "perpGapPct": -0.12117229056704013,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 82,
      "policy": "NORMAL",
      "evidence": [
        "true gap 0.02% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "META",
    "cert": {
      "ticker": "META",
      "trueGapPct": 0.00606785596645028,
      "perpGapPct": -0.1860119047619126,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 67,
      "policy": "NORMAL",
      "evidence": [
        "true gap 0.01% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "SPY",
    "cert": {
      "ticker": "SPY",
      "trueGapPct": 0.003347885475530608,
      "perpGapPct": -0.13172851889000517,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 74,
      "policy": "NORMAL",
      "evidence": [
        "true gap 0.00% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "QQQ",
    "cert": {
      "ticker": "QQQ",
      "trueGapPct": -0.23130926454475853,
      "perpGapPct": -0.3990466094542367,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 74,
      "policy": "NORMAL",
      "evidence": [
        "true gap -0.23% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "SQQQ",
    "cert": {
      "ticker": "SQQQ",
      "trueGapPct": -0.04070556309362434,
      "perpGapPct": -0.05426672093339608,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 74,
      "policy": "NORMAL",
      "evidence": [
        "true gap -0.04% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "TQQQ",
    "cert": {
      "ticker": "TQQQ",
      "trueGapPct": 0.024153130849564407,
      "perpGapPct": 0.024153130849564407,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 74,
      "policy": "NORMAL",
      "evidence": [
        "true gap 0.02% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "PLTR",
    "cert": {
      "ticker": "PLTR",
      "trueGapPct": 0.007800920508612922,
      "perpGapPct": -0.15965110392898446,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 59,
      "policy": "NORMAL",
      "evidence": [
        "true gap 0.01% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "CRCL",
    "cert": {
      "ticker": "CRCL",
      "trueGapPct": -0.03814367450731231,
      "perpGapPct": -0.2790461694571269,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 74,
      "policy": "NORMAL",
      "evidence": [
        "true gap -0.04% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "HOOD",
    "cert": {
      "ticker": "HOOD",
      "trueGapPct": 0.0562008242787449,
      "perpGapPct": -0.11688250970124832,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 74,
      "policy": "NORMAL",
      "evidence": [
        "true gap 0.06% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "MSTR",
    "cert": {
      "ticker": "MSTR",
      "trueGapPct": -0.017830874158602076,
      "perpGapPct": -0.004458314757017791,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 74,
      "policy": "NORMAL",
      "evidence": [
        "true gap -0.02% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "ORCL",
    "cert": {
      "ticker": "ORCL",
      "trueGapPct": -0.01887097643823615,
      "perpGapPct": -0.06467085230794349,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 74,
      "policy": "NORMAL",
      "evidence": [
        "true gap -0.02% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "NFLX",
    "cert": {
      "ticker": "NFLX",
      "trueGapPct": 0.00646830530402285,
      "perpGapPct": -0.12273901808785381,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 59,
      "policy": "NORMAL",
      "evidence": [
        "true gap 0.01% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "BABA",
    "cert": {
      "ticker": "BABA",
      "trueGapPct": -0.023654082694665034,
      "perpGapPct": -0.08037825059101064,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 74,
      "policy": "NORMAL",
      "evidence": [
        "true gap -0.02% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  },
  {
    "ticker": "GME",
    "cert": {
      "ticker": "GME",
      "trueGapPct": 0.02314814814814354,
      "perpGapPct": -0.04626416840158021,
      "classification": "FAIR",
      "qualityGrade": "?",
      "safetyScore": 74,
      "policy": "NORMAL",
      "evidence": [
        "true gap 0.02% within normal"
      ]
    },
    "anchorStale": false,
    "anchorSource": "LAST_CLOSE"
  }
];
